### ISSUE TITLE
Error ao passar os fragments

### ISSUE THREAD

**Issue by miguelslemos** [viniciusthiengo/tc-material-design#1]
Ao entrar na aplicação e deslizar 3 TABS para a direita e voltar para a primeira TAB de todos os carros não faz a requisição e fica com progress na tela para sempre. Só fazendo o swipe para recarregar 
![erro](https://cloud.githubusercontent.com/assets/11746181/9289405/b05f33bc-4344-11e5-888e-338cd7827f27.png)

**Comment by viniciusthiengo** [comment]
Fala Miguel, blz?
Corrigido o bug, coloque a validação de lista no onActivityCreated(), porém
a chamada ao Volley ficou no onResume(), assim funcionou sem problemas. Já
está atualizado no GitHub (
https://github.com/viniciusthiengo/tc-material-design). Abraço

Em 15 de agosto de 2015 11:57, miguelslemos notifications@github.com
escreveu:

> Ao entrar na aplicação e deslizar 3 TABS para a direita e voltar para a
> primeira TAB de todos os carros não faz a requisição e fica com progress na
> tela para sempre. Só fazendo o swipe para recarregar
> [image: erro]
> https://cloud.githubusercontent.com/assets/11746181/9289405/b05f33bc-4344-11e5-888e-338cd7827f27.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viniciusthiengo/tc-material-design/issues/1.

## 

Att,
Vinícius Thiengo
http://www.thiengo.com.br

**Comment by miguelslemos** [comment]
closed
