### ISSUE TITLE
isLastItem nunca volta a ser falso

### ISSUE THREAD

**Issue by miguelslemos** [viniciusthiengo/tc-material-design#2]
Opa Thiengo tudo bom?, percebi que o isLastItem uma vez que vira true não volta a ser falso, com isso se você andar pelos fragments e voltar para a primeira que tem mais carros só carrega os mais novos quando você da scroll para baixo para carregas os mais antigos ele não carrega pois não entra na condição  `if (!isLastItem
                        && mList.size() == llm.findLastCompletelyVisibleItemPosition() + 1
                        && (mSwipeRefreshLayout == null || !mSwipeRefreshLayout.isRefreshing()))`  

minha solução rápida foi  no doAfter() `if (jsonArray.length() == 0 && auxPosition == 0) {
                    isLastItem = true;
                }else{
                    isLastItem = false;
                }`

**Comment by viniciusthiengo** [comment]
Fala Miguel, blz sim.
Show de bola, nem me toquei nisso. Abraço

Att,
Vinícius Thiengo
http://www.thiengo.com.br

Em 20 de setembro de 2015 15:01, miguelslemos notifications@github.com
escreveu:

> Opa Thiengo tudo bom?, percebi que o isLastItem uma vez que vira true não
> volta a ser falso, com isso se você andar pelos fragments e voltar para a
> primeira que tem mais carros só carrega os mais novos quando você da scroll
> para baixo para carregas os mais antigos ele não carrega pois não entra na
> condição if (!isLastItem
> && mList.size() == llm.findLastCompletelyVisibleItemPosition() + 1
> && (mSwipeRefreshLayout == null || !mSwipeRefreshLayout.isRefreshing()))
> 
> minha solução rápida foi no doAfter() if (jsonArray.length() == 0 &&
> auxPosition == 0) {
> isLastItem = true;
> }else{
> isLastItem = false;
> }
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/viniciusthiengo/tc-material-design/issues/2.

## 

Att,
Vinícius Thiengo
http://www.thiengo.com.br

**Comment by viniciusthiengo** [comment]
Corrigido na versão mais atual no GitHub.
